Reminiscence Vex 패턴
junu192857/Vexatonic-Dash pull request #105
Opened 2024-02-15 22:38 UTC by vexatone

내가 도대체 어떤 쓰레기를 만든 거지

2024-02-15 22:39 UTC, vexatone commented
추천 설정: Scroll Speed 4 이상

2024-02-17 17:45 UTC, junu192857 requested changes
채보가 너무 어려워요

2024-02-18 18:54 UTC, vexatone commented
카메라 무빙까지 넣어봤음

(참고로 Vex 난이도에는 카메라가 360도 도는 구간이 있음)

2024-02-18 19:18 UTC, vexatone commented
난이도는 개인적으로 2 / 4 / 6~7 정도라고 생각함
Vex 채보는 클리어 난이도랑 스코어링 난이도가 다른 것 같은데 뭐 기준으로 매길까

2024-02-18 19:19 UTC, vexatone commented
참고로 누구도 못 깨는 그 채보는 Hell.txt로 넣어놨음 (더미 데이터)

2024-02-18 19:38 UTC, junu192857 commented
내 체감난이도는 2/5/8이긴 한데 일단 채보 다 만들고 나서 다같이 난이도 평가를 다시한번 쭉 해보자

2024-02-18 19:38 UTC, junu192857 approved these changes
굿

2024-02-19 02:50 UTC, merged