Keyboard control WIP
junu192857/Vexatonic-Dash pull request #107
Opened 2024-02-17 11:40 UTC by Mathshyun

메인 화면에서 키보드 조작(상하 방향키, 좌우 방향키, 엔터, ESC) 작업 중

이후 작업에서 충돌 날 수도 있으니까 미리 PR 올림

진행 상황:
- 상하 방향키로 이동
- 좌우 방향키로 값 조절
- ESC로 돌아가기

해야 하는 것:
- 엔터 눌러서 실행할 것 지정 ~~노가다~~
- 현재 선택된 버튼 강조

2024-02-17 12:53 UTC, junu192857 requested changes
다른 창 들어갔다 Esc 눌러서 나왔을 때 선택된 버튼이 초기화되지 않았으면 좋겠음

2024-02-18 14:01 UTC, vexatone commented
일단은 잘 돌아가는 것 같네요
선택된 키 강조도 잘 부탁함

2024-02-18 14:35 UTC, Mathshyun commented
선택된 키 강조 추가함
버튼 등장 직후에는 강조된 버튼이 없는데 이는 기술적 어려움(해결하기 귀찮음)의 문제로 미구현됨

2024-02-18 14:57 UTC, junu192857 approved these changes

2024-02-18 14:58 UTC, merged