Dash 노트 구현, 카메라 이동 구현, FPS 표시 기능 추가
junu192857/Vexatonic-Dash pull request #28
Opened 2024-01-25 08:56 UTC by junu192857

아 정기모임 시작하기 귀찮다

2024-01-25 09:04 UTC, vexatone requested changes
확인 부탁

2024-01-25 09:04 UTC, vexatone commented on Vexatonic_Dash/Assets/Scripts/LevelReader.cs
> +                        if (list.TryPeek(out NoteSpawnInfo prev)) prev.platformScale = (float)(2 * (cur.spawnTime - prev.spawnTime));
prev를 여기서 선언하면 첫 노트가 대시일 때 에러가 터질 것으로 보임

2024-01-25 09:04 UTC, vexatone commented on Vexatonic_Dash/Assets/Scripts/LevelReader.cs
> +                        if (list.TryPeek(out prev)) prev.platformScale *= (float)(2 * (cur.spawnTime - prev.spawnTime));
74번 줄과 마찬가지

2024-01-25 09:04 UTC, vexatone commented on Vexatonic_Dash/Assets/Scripts/LevelReader.cs
> +                        cur = new NoteSpawnInfo(spawnTime, (NoteType)((int)type - 65), float.Parse(myList[4]));
72번 줄과 마찬가지

2024-01-25 09:04 UTC, vexatone commented on Vexatonic_Dash/Assets/Scripts/LevelReader.cs
> +                        NoteSpawnInfo cur = new NoteSpawnInfo(spawnTime, (NoteType)((int)type - 65), 1f);
굳이 NoteType 부분을 저렇게 쓸 이유가 있을지 모르겠음. 'A'일 때만 실행되는 파트로 보이는데 그러면 NoteType를 직접 넘겨주는 게 나을 수도?

2024-01-25 11:43 UTC, Mathshyun requested changes

2024-01-25 11:43 UTC, Mathshyun commented on Vexatonic_Dash/Assets/Scripts/RhythmManager.cs
> +        noteList = lr.ParseFile(Application.dataPath + "\\Levels\\test.txt");
디렉토리 구분 기호는 슬래시(`/`)로 해 주세요
역슬래시는 macOS에서 인식을 못 함

2024-01-27 01:31 UTC, junu192857 commented on Vexatonic_Dash/Assets/Scripts/LevelReader.cs
> +                        NoteSpawnInfo cur = new NoteSpawnInfo(spawnTime, (NoteType)((int)type - 65), 1f);
모든 노트를 한 번에 처리하려던 코드의 잔재
수정 완료

2024-01-27 01:51 UTC, vexatone commented
굿

2024-01-27 01:52 UTC, vexatone approved these changes
굿

2024-01-27 12:38 UTC, junu192857 commented on Vexatonic_Dash/Assets/Scripts/RhythmManager.cs
> +        noteList = lr.ParseFile(Application.dataPath + "\\Levels\\test.txt");
변경완료

2024-01-27 12:38 UTC, merged